title: Attach an Explorer HAT 
hero_image: images/banner.png
description: Learn how to attach an Explorer HAT to a Raspberry Pi
original_url:
theme: cc-prototype
duration: 1
theme: cc-prototype
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "explorer hat, raspberry pi"
steps:
  - title: Attach an Explorer HAT
